// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyVNsWHdFxPyCfP9oiRQqpulsGjUSdnYI',
    appId: '1:360509427650:web:1202c1888dc58b695e505b',
    messagingSenderId: '360509427650',
    projectId: 'flutter-video-conference-3e0cb',
    authDomain: 'flutter-video-conference-3e0cb.firebaseapp.com',
    storageBucket: 'flutter-video-conference-3e0cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4qtv_kJdC6--05RA6r63LHQ77NZhGLQ',
    appId: '1:360509427650:android:e2704b0dae6b38855e505b',
    messagingSenderId: '360509427650',
    projectId: 'flutter-video-conference-3e0cb',
    storageBucket: 'flutter-video-conference-3e0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHvYji0nTiaSqxVMtxYS5_ciJHl-TM6so',
    appId: '1:360509427650:ios:86f5efe6084149855e505b',
    messagingSenderId: '360509427650',
    projectId: 'flutter-video-conference-3e0cb',
    storageBucket: 'flutter-video-conference-3e0cb.firebasestorage.app',
    iosBundleId: 'com.video.conference.flutterVideoConference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHvYji0nTiaSqxVMtxYS5_ciJHl-TM6so',
    appId: '1:360509427650:ios:86f5efe6084149855e505b',
    messagingSenderId: '360509427650',
    projectId: 'flutter-video-conference-3e0cb',
    storageBucket: 'flutter-video-conference-3e0cb.firebasestorage.app',
    iosBundleId: 'com.video.conference.flutterVideoConference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyVNsWHdFxPyCfP9oiRQqpulsGjUSdnYI',
    appId: '1:360509427650:web:971862c0c87a6c935e505b',
    messagingSenderId: '360509427650',
    projectId: 'flutter-video-conference-3e0cb',
    authDomain: 'flutter-video-conference-3e0cb.firebaseapp.com',
    storageBucket: 'flutter-video-conference-3e0cb.firebasestorage.app',
  );
}
